# site_name: LearningCS
# site_url: https://liusy58.github.io/LearningCS/
# repo_url: https://github.com/liusy58/LearningCS
# copyright: |
#   <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>.
# extra:
#   analytics:
#     provider: google
#     property: G-C7E0KYN4VG
# theme:
#   icon:
#     repo: fontawesome/brands/github
#   name: material
#   custom_dir: docs/overrides
#   language: zh
#   features:
#     - navigation.top
#   palette:
#     - media: "(prefers-color-scheme: light)"
#       scheme: default
#       toggle:
#         icon: material/weather-night
#         name: 夜间模式
#     - media: "(prefers-color-scheme: dark)"
#       scheme: slate
#       toggle:
#         icon: material/weather-sunny
#         name: 白天模式
# plugins:
#   - search
#   - git-authors
#   - git-revision-date-localized:
#       type: iso_datetime
#       timezone: Asia/Shanghai
# markdown_extensions:
#   - pymdownx.highlight:
#       anchor_linenums: true
#   - pymdownx.details
#   - pymdownx.superfences:
#       custom_fences:
#         - name: mermaid
#           class: mermaid
#           format: !!python/name:pymdownx.superfences.fence_code_format  
#   - pymdownx.tabbed
#   - pymdownx.keys
#   - pymdownx.snippets
#   - pymdownx.inlinehilite
#   - footnotes
#   - admonition
#   - pymdownx.critic
#   - pymdownx.caret
#   - pymdownx.keys
#   - pymdownx.mark
#   - pymdownx.tilde
#   - pymdownx.arithmatex:
#       generic: true        
#   - toc:
#       permalink: true
#       slugify: !!python/name:pymdownx.slugs.uslugify
#   - pymdownx.emoji:
#       emoji_index: !!python/name:materialx.emoji.twemoji
#       emoji_generator: !!python/name:materialx.emoji.to_svg
#   - pymdownx.tasklist:
#       custom_checkbox: true    
# extra_javascript:
#   - javascripts/mathjax.js
#   - https://polyfill.io/v3/polyfill.min.js?features=es6
#   - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


site_name: LearningCS
site_url: https://liusy58.github.io/LearningCS/
repo_url: https://github.com/liusy58/LearningCS
copyright: |
  <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>.
extra:
  analytics:
    provider: google
    property: G-C7E0KYN4VG
theme:
  icon:
    repo: fontawesome/brands/github
  name: material
  custom_dir: docs/overrides
  language: zh
  features:
    - navigation.top
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: 夜间模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: 白天模式
plugins:
  - search
  - git-authors
  - git-revision-date-localized:
      type: iso_datetime
      timezone: Asia/Shanghai
  - exclude:
      glob:
        - "*.md"
        - "*.pdf"
        - "*.gz"      
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - footnotes
  - admonition
  - toc:
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra_css:
  - stylesheets/extra.css


nav:
  - Reading List:
    - Compilers: "ReadingList/Compilers.md"
    - CS143: "Compiler/CS143.md"